---
title: "Alluvial"
author: "Arvind Venkatadri"
date: "16/07/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(ggalluvial)

```


## UC Berkeley Admissions dataset.

Do we see a case for gender bias in admissions?

Following this vignette:
<https://cran.r-project.org/web/packages/ggalluvial/vignettes/ggalluvial.html>

```{r}
head(as.data.frame(UCBAdmissions),n = 12)
is_alluvia_form(as.data.frame(UCBAdmissions),axes = 1:3)
```


```{r}
ucb <- as.data.frame(UCBAdmissions)
glimpse(ucb)
ggplot(ucb, aes( y = Freq, axis1 = Gender, axis2 = Dept, axis3 = Admit)) +
  geom_alluvium(aes(fill = Gender),width = 1/12) + 
  geom_stratum(width = 1/5, fill = "black", color = "grey") +
  geom_label(stat = "stratum", infer.label = TRUE) + 
  scale_x_discrete(limits = c("Gender","Dept", "Admitted?"),expand = c(0.05, 0.05))+
  scale_fill_brewer(type = "qual", palette = "Set1") +
  ggtitle("UC Berkeley admissions and rejections, by sex and department")
```



```{r Titanic Alluvial Plot}

titanic <- as.data.frame(Titanic)
glimpse(titanic)
ggplot(titanic,
       aes(y = Freq, # No of people defined by each category
           axis3 = Survived, axis2 = Sex, axis1 = Class)) + # Categories
  geom_alluvium(aes(fill = Class),
                # width = 0, knot.pos = 0, reverse = FALSE
                ) +
  guides(fill = FALSE) +
  geom_stratum( ) + #width = 1/3, reverse = FALSE) +
  geom_text(stat = "stratum", aes(label = after_stat(stratum))) + #infer.label = TRUE, reverse = FALSE) +
  scale_x_continuous(breaks = 1:3, labels = c("Class","Sex", "Survived")) +
  # coord_flip() +
  ggtitle("Titanic survival by class and sex")
```




```{r A college like ours-1}
data("majors")
majors
set.seed(1234)
majors$curriculum <- as.factor(majors$curriculum)
glimpse(majors)
```

```{r So what are the most popular courses}

ggplot(majors, aes(x = semester,
                   stratum = curriculum, 
                   alluvium = student, 
                   fill = curriculum, 
                   label = curriculum)) + 
  geom_flow(stat = "alluvium", color = "darkgrey") +
  geom_stratum()+
  scale_fill_brewer(type = "qual", palette = "Set2") +
  theme(legend.position = "bottom") +
  ggtitle("student curricula across several semesters")
```


```{r ab initio}
GSK <- c("VTT", "DTT", "SCT", "DM")
CE <- c("P&I", "O&C", "B&C", "C&P", "F&S")
# CE2 <- c("CE21", "CE22", "CE23", "CE24")
# CE3 <- c("CE31", "CE32", "CE33", "CE34")
# CE4 <- c("CE41", "CE42", "CE43", "CE44")
Majors <- c("CAP", "DMA", "Film", "HCD", "IADP", "IAIDP", "PSD", "VCSB")

data <- tibble(
  student = 1:100,
  Major = sample(Majors, size = 100, replace = TRUE),
  S1GSK = sample(GSK, size = 100, replace = TRUE),
  S1C1 = sample(CE, size = 100, replace = TRUE),
  S1C2 = sample(CE, size = 100, replace = TRUE),
  S2GSK = sample(GSK, size = 100, replace = TRUE),
  S2C1 = sample(CE, size = 100, replace = TRUE),
  S2C2 = sample(CE, size = 100, replace = TRUE)
)

data <- data %>% 
  pivot_longer(cols = c(S1GSK, S1C1,S1C2,S2GSK, S2C1,S2C2), names_to = "cycle", values_to = "class")
glimpse(data)
is_alluvia_form(data)

```


```{r Lets_plot_this}
ggplot(data = data, aes(x = cycle, stratum = class, alluvium = student, fill = class,label = class)) +
  geom_alluvium(color = "darkgrey") +
  geom_stratum() +
  geom_label(stat = "stratum", label.strata = TRUE)


ggplot(data,
       aes(x = cycle, stratum = class, alluvium = student,
           fill = class, label = class)) +
  geom_flow(stat = "alluvium", lode.guidance = "rightleft",
            color = "darkgray") +
  geom_stratum() +
  # theme(legend.position = "none") +
  theme_minimal() + 
  geom_label(stat = "stratum") + 
  ggtitle("Student Curricula across several Cycles")

```



Can we plot Alluvial Diagrams on a per Major basis? Then I can see if students in each major have multiple pathways through the FSP CE courses

```{r Per_Major_Alluvia}

## Can use "purrr" here. 

data %>% filter(Major == "HCD") %>% 
  ggplot(.,
       aes(x = cycle, stratum = class, alluvium = student,
           fill = class, label = class)) +
  geom_flow(stat = "alluvium", lode.guidance = "rightleft",
            color = "darkgray") +
  geom_stratum() +
  # theme(legend.position = "none") +
  theme_minimal() + 
  geom_label(stat = "stratum") + 
  ggtitle("HCD Student CE Pathways across several Cycles")
```

